### 책 목록 조회
GET http://localhost:8080/api/books
Accept: application/json

### 책 단건 조회
GET http://localhost:8080/api/books/1
Accept: application/json

### 책 등록
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "도메인 주도 설계",
  "author": "에릭 에반스",
  "summary": "DDD의 고전",
  "coverImageUrl": null
}

### 책 수정
PUT http://localhost:8080/api/books/1
Content-Type: application/json

{
  "title": "수정된 제목",
  "author": "수정된 저자",
  "content": "수정된 소개",
  "coverImageUrl": null
}

### 책 삭제
DELETE http://localhost:8080/api/books/1


### 존재하지 않는 책 조회
GET http://localhost:8080/api/books/9999
Accept: application/json
